### ISSUE TITLE
uuid module is still 3.4.0 at release version

### ISSUE THREAD

**Issue by markrity** [google/eventid-js#156]
Hi I have seen that you have upgraded uuid to version 8 and upper at `main` branch, but latest release `1.0.0` still uses 3.4.0.

Also `@google-cloud/logging` still uses eventid version 1.0.0 , so it didn't get this upgrade. 

```
warning @google-cloud/logging > eventid > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by JustinBeckwith** [comment]
Greetings - I just cut a release of this library in https://github.com/google/eventid-js/pull/130, and we'll make sure it gets rolled out to logging!

**Comment by markrity** [comment]
@JustinBeckwith Thank you :)
